import pandas as pd
import json
from exp.few_shot.scripts.prompts import prompt_guidance, get_prompt_template
from exp.few_shot.scripts.make_shot import make_identity
from utils.dataset_helper.get_data import grouping, METRICS

# dis_flag_score_to_text = {0:'agree', 1:'disagree'}
# writing_sty_score_to_text = {0:'inappropriate', 0.5: 'partially appropriate', 1:'appropriate'}
# relevance_score_to_text = {0:'irrelevant', 0.5: 'partially relevant', 1:'relevant'}
# completeness_score_to_text = {0:'incomplete response', 0.5: 'partially complete response', 1:'complete response'}
# factual_acc_score_to_text = {0:'inaccurate/missing critical information', 0.5: 'partially accurate', 1:'factually accurate'}
# overall_score_to_text = {0:'inaccurate/missing critical information', 0.5: 'partially accurate', 1:'factually accurate'}
def get_sft_prompt(metrics:list[str], llm_response:str, query:str):
    

    PROMPT = f"""You are an expert in dermatology and wound care. Think silently if needed.
Your job is to give accurate ratings of the response generated by an LLM. The response is an answer to the question about an image which contains either a skin disease or a wound.
You should thoroughly analyze the question, the response to the question and the image.
The output format must be a single number and the range is {0.0,0.5,1.0}. The name of metric you are going to rate is {metrics[0]}
{prompt_guidance(metrics=metrics)}

Now, I am going to give you the response and the question. Please analyze with the image.

The patient asks with the image: {query}. The LLM responds with:{llm_response}

Given the image, rate the LLM's response according to {metrics[0]} and the rules I just presented.

Remember to output a single number. You should choose from 0.0, 0.5 and 1.0 Do not add anything other than your rating.
"""
    
    return PROMPT

def per_entry_temp(image_path:str, output:str, metrics:list[str],key:dict, llm_response, query):
    entry_temp = {}
    entry_temp["messages"] = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": image_path
                },
                {
                    "type": "text",
                    "text": get_sft_prompt(metrics=metrics, llm_response=llm_response, query=query)

                },
            ],
        },
        {
            "role": "assistant",
            "content": [
                {
                    "type": "text",
                    "text": output
                },
            ],
        },
    ]

    entry_temp["key"] = key
    
    return entry_temp

def make_output(df:pd.DataFrame):
    # Extract labels
    disagree_flag = df[df['metric'] == 'disagree_flag']['label'].iloc[0]
    completeness = df[df['metric'] == 'completeness']['label'].iloc[0]
    factual_acc = df[df['metric'] == 'factual-accuracy']['label'].iloc[0]
    overall = df[df['metric'] == 'overall']['label'].iloc[0]    
    relevance = df[df['metric'] == 'relevance']['label'].iloc[0]  
    writing_style = df[df['metric'] == 'writing-style']['label'].iloc[0]

    # Create the dictionary with string values
    data = [{
        "disagree_flag": str(float(disagree_flag)),
        "completeness": str(float(completeness)),
        "factual-accuracy": str(float(factual_acc)),
        "relevance": str(float(relevance)),
        "writing-style": str(float(writing_style)),
        "overall": str(float(overall))
    }]

    # Convert the list to a JSON string without extra whitespace
    json_content = json.dumps(data)
    
    # Wrap in the specific markdown format you requested
    return f"```json\n{json_content}\n```"

def prepare_ft_input_per_row(train_df:pd.DataFrame, metrics:list[str]) -> list[str]:
    #right now it only supports 1 metric
    input = []
    train_df = train_df[train_df['metric'] == metrics[0]]
    metrics = metrics

    for key_val, group in train_df.iterrows():
        key = make_identity(group)

<<<<<<< HEAD
        label = str(group[group['metric'] == metrics[0]]['label'].iloc[0])
=======
        # label = group[group['metric'] == metrics[0]]['label'].iloc[0]
>>>>>>> master
        entry = per_entry_temp(image_path=group['image_path'].iloc[0],
                               output=label, 
                               key = key, 
                               metrics=metrics,
                               llm_response=group['candidate'].iloc[0],
                               query = group['query_text'].iloc[0])
        
        input.append(entry)

    return input

<<<<<<< HEAD
def prepare_ft_input(train_df:pd.DataFrame, metrics:list[str]) -> list[str]:
    #right now it only supports 1 metric
    input = []
    train_df = grouping(df = train_df, group_type=['metric'])
=======
def prepare_ft_input(train_df:pd.DataFrame, metrics:list[str], en_only:bool = True) -> list[str]:
    #right now it only supports 1 metric
    input = []
    if en_only:
        train_df = train_df[train_df['lang'] == 'en']

    train_df = grouping(df = train_df, group_type=['metric'])

>>>>>>> master
    metrics = metrics

    for key_val, group in train_df:
        key = make_identity(group)
<<<<<<< HEAD

        label = str(group[group['metric'] == metrics[0]]['label'].iloc[0])
=======
        # print(group)
        # print(group[group['metric'] == metrics[0]])
        label = group[group['metric'] == metrics[0]]['label'].iloc[0]
        # print(label)
>>>>>>> master
        entry = per_entry_temp(image_path=group['image_path'].iloc[0],
                               output=label, 
                               key = key, 
                               metrics=metrics,
                               llm_response=group['candidate'].iloc[0],
                               query = group['query_text'].iloc[0])
        
        input.append(entry)

    return input
        
        
if __name__ == "__main__":

    ###-----prepare SFT data-----###
    metrics = ['writing-style']

    train_df = pd.read_csv("exp/few_shot/datasets/train.csv")
    val_df = pd.read_csv("exp/few_shot/datasets/val.csv")

    train_output_path = "exp/finetune/data/new_temp/train_ft_input.json"
    val_output_path = "exp/finetune/data/new_temp/val_ft_input.json"

    samp_train_output_path = "my_test/temp/samp_train_ft_input.json"
    samp_val_output_path = "my_test/temp/samp_val_ft_input.json"

    train_ft_input = prepare_ft_input(train_df = train_df, metrics=metrics)
    val_ft_input = prepare_ft_input(train_df = val_df, metrics=metrics)
    
    #save all data
    with open(train_output_path, 'w') as f:
        json.dump(train_ft_input, f, indent=2)

    with open(val_output_path, 'w') as f:
        json.dump(val_ft_input, f, indent=2)

    with open(samp_train_output_path, 'w') as f:
        json.dump(train_ft_input[0:10], f, indent=2)

    with open(samp_val_output_path, 'w') as f:
        json.dump(val_ft_input[0:10], f, indent=2)

    ###-----prepare inference data-----###











    
