from exp.few_shot.scripts.make_shot import prepare_shots
from exp.few_shot.scripts.split_shot_df import split_shot
import pandas as pd
from utils.dataset_helper.get_data import *
import json

def prompt():
    PROMPT = """
You are an assistant for a senior doctor with expertise in dermatology and woundcare. 
Your job is to give your explanation about the criteria used by the experts to rate the response generated by VLMs.

The response generated by the VLM is an answer to the quetion about an image which contains either a skin disease or a wound. 
The known criteria is as follows:
There are six ratings given by the experts:

    disagree_flag:put 1 if disagree with an answer, 0 otherwise

    completeness:put 1 for perfect completeness, 0.5 partial, 0 not complete

    factual_accuracy:Has all necessary information required to give been given to the patient based on the question present?
                        "1 is for perfect factual accuracy, 0.5 partial, 0 for not accurate.
    
    overall: Is everything in the response medically accurate (regardless on if it is complete or relevant)
    1 is for perfect medical accuracy, 0.5 partial, 0 for not accurate.
    
    relevance: 1 for relevant answer to the question, 0.5 partially relevant, 0.0 irrelevant information

    writing style: 1 for appropriate writing style, 0.5 partial, 0 otherwise

    In general for a guide on number ratings:

    0: Terrible response (incorrect or/and harmful). May lead to grievous misinformation or dangerous outcomes. Should never be shown to the patient.

    0.5: Response relevant and will not necessary cause harm but missing critical items or containing incorrect information. Should not be shown to the patient before correction.

    1: Response gives complete and accurate answers. Can be safely presented to a patient


However, the rating rules above is not specific enough for your senior doctor to give accurate ratings. You will be given lots of samples containing:1. the response 2.the question 3. the image 4.the ratings 
Based on these samples, you should give a very detailed explanation on how the senior doctor that you are assisting should rate new samples.
You should think very carefully and come up with hypothesis on the true rating rules.

Your output should contain detailed explanations on how your senior doctor should rate disagree_flag, completeness, factual accuracy, overall, relevance and writing style.

HERE are the samples
"""

    return PROMPT

def prepare_shots(shot_df: pd.DataFrame, metrics, exclude_image:bool = False):

    num_shot_img = int(len(shot_df) / len(metrics))

    # df = pd.concat([shot_df, infer_df]).reset_index(drop=True)
    # print(infer_df)
    grouped_shot_df = grouping(shot_df, group_type=['metric'])

    shot_key_cols = list(grouped_shot_df.grouper.names)

    # 2. Find the exact index of the path column
    path_col_name = 'image_path' 
    shot_path_idx = shot_key_cols.index(path_col_name)

    #for storing
    group_shot_list = []
    keys_shot_img_path = []

    for key_vals, group in grouped_shot_df:
        group_shot_list.append(group)
        keys_shot_img_path.append(key_vals[shot_path_idx])

    shot_groups = group_shot_list


    # print(infer_groups)

    content = [{"type": "text", "text": prompt()}]
    
    img_index = 0
    for s in shot_groups:
        shot_query = s['query_text'].iloc[0]
        shot_response = s['candidate'].iloc[0]
        
        # build few-shot example
        rating_string = ""
        for m in metrics:
            metric_value = s['label'][s['metric'] == m].iloc[0]
            rating_string += f"{m}: {metric_value}\n"

        example_string = f"Image {img_index + 1}:\nQuery:\n\"{shot_query}\"\n\nLLM response:\n\"{shot_response}\"\nRatings:\n{rating_string}"
        # if not exclude_image:
        #     example_string = f"Image {img_index + 1}:\nQuery:\n\"{shot_query}\"\n\nLLM response:\n\"{shot_response}\"\nRatings:\n{rating_string}"
        # else:
        #     example_string=f"Query:\n\"{shot_query}\"\n\nLLM response:\n\"{shot_response}\"\nRatings:\n{rating_string}"

        content.append({"type": "text", "text": example_string})

        if not exclude_image:
            content.append({"type": "image", "image": keys_shot_img_path[img_index]})
        img_index += 1
    return {
            "role": "user",
            "content": content,
            "key": None
        }

if __name__ == "__main__":
    save_path = "exp/reinforced_few_shot/explain_shot7_short.json"
    shot_df = split_shot(split_from="exp/few_shot/datasets/train.csv", shot_num=7, metrics=METRICS, save_path=None)
    input_json = [prepare_shots(shot_df=shot_df,metrics=METRICS,exclude_image=False)]

    with open(save_path, 'w') as f:
        json.dump(input_json, f, indent=2)



