import json
import pandas as pd
from utils.dataset_helper.get_data import *
from exp.few_shot.scripts.make_shot import make_identity, prepare_shots

def prompt():
    PROMPT = """
You are an assistant for a senior doctor with expertise in dermatology and woundcare. 
Your job is to give your explanation about the criteria used by the experts to rate the response generated by VLMs.

The response generated by the VLM is an answer to the quetion about an image which contains either a skin disease or a wound. 
The known criteria is as follows:
There are two ratings: writing-style and overall accuracy. For writing style, the experts would rate the response 1 if it is in an appropriate writing style, 0.5 partially appropriate , 0 for not appropriate. 
For overall accuracy, you should rate the response 1 for complete answer to question, 0.5 partial, 0.0 inaccurate/missing critical information.

In general for a guide on number ratings:

0: Terrible response (incorrect or/and harmful). May lead to grievous misinformation or dangerous outcomes. Should never be shown to the patient.

0.5: Response relevant and will not necessary cause harm but missing critical items or containing incorrect information. Should not be shown to the patient before correction.

1: Response gives complete and accurate answers. Can be safely presented to a patient

The problem is that the criteria above is too vague. Your explanation about the true criteria should be specific and informative which is critical for the senior doctor to accurately rate the response.
I will provide you a few examples containing:1. the response 2.the question 3. the image 4.the ratings 

After that, I will give you a sample containing 1. the response 2.the question 3. the image 4.the ratings, then you need to give your explanations

The output format must be strict JSON, with the following structure:

[
  {
    "writing_style": YOUR EXPLANATION TO WHY THE DOCTOR GAVE THE SCORE,
    "overall": YOUR EXPLANATION TO WHY THE DOCTOR GAVE THE SCORE
  }
]



"""

    return PROMPT

def back_prompt():
    PROMPT = """
        now give the explanation to the response below.
        The output format must be strict JSON, with the following structure:

        [
        {
            "writing_style": YOUR EXPLANATION TO WHY THE DOCTOR GAVE THE SCORE,
            "overall": YOUR EXPLANATION TO WHY THE DOCTOR GAVE THE SCORE
        }
        ]

"""
    return PROMPT

def prepare_inputs(infer_df:pd.DataFrame,shot_df: pd.DataFrame, metrics):

    num_shot_img = int(len(shot_df) / len(metrics))

    base_prompt = prompt()
    # df = pd.concat([shot_df, infer_df]).reset_index(drop=True)
    # print(infer_df)
    grouped_shot_df = grouping(shot_df, group_type=['metric'])
    grouped_infer_df = grouping(infer_df, group_type = ['metric'])

    group_shot_list = []
    keys_shot_img_path = []

    group_infer_list = []
    keys_infer_img_path = []

    for key_vals, group in grouped_shot_df:
        group_shot_list.append(group)
        keys_shot_img_path.append(key_vals[-2])

    for key_vals, group in grouped_infer_df:
        group_infer_list.append(group)
        keys_infer_img_path.append(key_vals[-2])

    shot_groups = group_shot_list
    infer_groups = group_infer_list

    if infer_groups is None:
        print("found")

    # print(infer_groups)

    content = [{"type": "text", "text": base_prompt}]
    
    img_index = 0
    for s in shot_groups:
        shot_query = s['query_text'].iloc[0]
        shot_response = s['candidate'].iloc[0]
        
        # build few-shot example
        rating_string = ""
        for m in metrics:
            
            metric_value = s['label'][s['metric'] == m].iloc[0]
            rating_string += f"{m}: {metric_value}\n"

        example_string = f"Image {img_index + 1}:\nQuery:\n\"{shot_query}\"\n\nLLM response:\n\"{shot_response}\"\nRatings:\n{rating_string}"
        
        content.append({"type": "text", "text": example_string})
        content.append({"type": "image", "image": keys_shot_img_path[img_index]})
        img_index += 1

    infer_index = 0
    content.append({"type": "text", "text": back_prompt()})
    
    for i in infer_groups:
        infer_query = i['query_text'].iloc[0] if isinstance(i, pd.DataFrame) else i['query_text']
        infer_response = i['candidate'].iloc[0] if isinstance(i, pd.DataFrame) else i['candidate']

        rating_string = ""
        for m in metrics:
            metric_value = s['label'][s['metric'] == m].iloc[0]
            rating_string += f"{m}: {metric_value}\n"

        infer_index += 1
        infer_section = f"Image {num_shot_img + infer_index}:\nQuery:\n\"{infer_query}\"\n\nLLM response:\n\"{infer_response}\"\nRatings:\n{rating_string}"
        content.append({"type": "text", "text": infer_section})
        content.append({"type": "image", "image": keys_infer_img_path[infer_index - 1]})
        # print(infer_query)


    return {
            "role": "user",
            "content": content,
            "key": None
        }

if __name__ == "__main__":
    metrics = ['writing-style', 'overall']

    shot_df = pd.read_csv("exp/reinforced_few_shot/datasets/augmented_shot.csv")
    infer_df = pd.read_csv("exp/reinforced_few_shot/datasets/infer_sample.csv")
    # _, infer_df = retrieve_data(df = aligned_df,lang = ['en'], sample_n=0, system = ['1','2','3']) 
    llm_input = []
    #group the inference dataframe so that every iteration is a sample 
    infer_group = grouping(df = infer_df, group_type=['metric'])
    
    
    group_keys = []
    for key_val,infer in infer_group:
        # print(infer['label'].iloc[0])
        shot = prepare_inputs(infer_df = infer, shot_df=shot_df,metrics=metrics)
        key = make_identity(infer)

        shot["key"] = key
        llm_input.append(shot)
        group_keys.append(key_val)
    

    with open('exp/reinforced_few_shot/shots/shots.json', "w", encoding="utf-8") as f:
        json.dump(llm_input, f, indent=2, ensure_ascii=False)

    print(len(llm_input))


